"""
Quick inspection script for X.npy and y.npy generated by
convert_fsl_to_npy.py.

Loads both files and prints their shapes, dtypes, sample values,
and per-class counts so you can confirm the conversion worked
correctly before training.
"""

import numpy as np
from collections import Counter

X_PATH = "X.npy"
Y_PATH = "y.npy"

X = np.load(X_PATH)
y = np.load(Y_PATH)

print("=== X.npy ===")
print(f"Shape: {X.shape}")   # expect (N, 21, 3)
print(f"Dtype: {X.dtype}")
print(f"Min value: {X.min():.4f}")
print(f"Max value: {X.max():.4f}")
print(f"Sample (first entry, all 21 landmarks):\n{X[0]}")

print("\n=== y.npy ===")
print(f"Shape: {y.shape}")   # expect (N,)
print(f"Dtype: {y.dtype}")
print(f"Unique labels: {sorted(set(y))}")
print(f"Number of classes: {len(set(y))}")

print("\n=== Per-class counts ===")
counts = Counter(y)
for label in sorted(counts):
    print(f"  {label}: {counts[label]}")

print("\n=== Sanity checks ===")
assert X.shape[0] == y.shape[0], "Mismatch: X and y have different sample counts!"
assert X.shape[1:] == (21, 3), f"Unexpected landmark shape: {X.shape[1:]} (expected (21, 3))"
print("All checks passed. X and y are aligned and correctly shaped.")